on:
  workflow_dispatch:
  schedule:
    - cron: '45 7 * * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: li1ht2ay-3es/re1ro2rc3@cron
        with:
          token: ${{ secrets.token }}
